/**
 * these items may individually be subject to a different license than
 * the main project. See the LICENSE file in this directory for more details.
 *
 * To the best of my ability, I've included comments describing the source of
 * each group of items.
 */

export const clearEmotions = [
  // Cleaned up from https://en.wikipedia.org/wiki/Template:Emotion.
  // License: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License
  'Acceptance',
  'Affection',
  'Anger',
  'Angst',
  'Anguish',
  'Annoyance',
  'Anticipation',
  'Anxiety',
  'Apathy',
  'Arousal',
  'Awe',
  'Boredom',
  'Confidence',
  'Contempt',
  'Contentment',
  'Courage',
  'Curiosity',
  'Depression',
  'Desire',
  'Despair',
  'Disappointment',
  'Disgust',
  'Distrust',
  'Ecstasy',
  'Embarrassment',
  'Empathy',
  'Enthusiasm',
  'Envy',
  'Euphoria',
  'Fear',
  'Frustration',
  'Gratitude',
  'Grief',
  'Guilt',
  'Happiness',
  'Hatred',
  'Hope',
  'Horror',
  'Hostility',
  'Humiliation',
  'Interest',
  'Jealousy',
  'Joy',
  'Loneliness',
  'Love',
  'Lust',
  'Outrage',
  'Panic',
  'Passion',
  'Pity',
  'Pleasure',
  'Pride',
  'Rage',
  'Regret',
  'Social connection',
  'Rejection',
  'Remorse',
  'Resentment',
  'Sadness',
  'Self-confidence',
  'Shame',
  'Shock',
  'Shyness',
  'Sorrow',
  'Suffering',
  'Surprise',
  'Trust',
  'Wonder',
  'Worry',
];

export const emotionalDyads = [
  // Cleaned up from https://en.wikipedia.org/wiki/Contrasting_and_categorization_of_emotions.
  // Wiki's source: Plutchik's wheel of emotions.
  // License: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License
  'Optimism\n(anticipation + joy)',
  'Hope\n(anticipation + trust)',
  'Anxiety\n(anticipation + fear)',
  'Love\n(joy + trust)',
  'Guilt\n(joy + fear)',
  'Delight\n(joy + surprise)',
  'Submission\n(trust + fear)',
  'Curiosity\n(trust + surprise)',
  'Sentimentality\n(trust + sadness)',
  'Awe\n(fear + surprise)',
  'Despair\n(fear + sadness)',
  'Shame\n(fear + disgust)',
  'Disapproval\n(surprise + sadness)',
  'Unbelief\n(surprise + disgust)',
  'Outrage\n(surprise + anger)',
  'Remorse\n(sadness + disgust)',
  'Envy\n(sadness + anger)',
  'Pessimism\n(sadness + anticipation)',
  'Contempt\n(disgust + anger)',
  'Cynicism\n(disgust + anticipation)',
  'Morbidness\n(disgust + joy)',
  'Aggressiveness\n(anger + anticipation)',
  'Pride\n(anger + joy)',
  'Dominance\n(anger + trust)',
];

export const groupedEmotions = [
  // Cleaned up from https://en.wikipedia.org/wiki/Contrasting_and_categorization_of_emotions
  // Wiki's source: Parrott's emotions by groups.
  // License: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License
  'Love',
  'Affection',
  'Adoration',
  'Fondness',
  'Liking',
  'Attraction',
  'Caring',
  'Tenderness',
  'Compassion',
  'Sentimentality',
  'Lust',
  'Desire',
  'Passion',
  'Infatuation',
  'Longing',

  'Joy',
  'Cheerfulness',
  'Amusement',
  'Bliss',
  'Gaiety',
  'Glee',
  'Jolliness',
  'Joviality',
  'Joy',
  'Delight',
  'Enjoyment',
  'Gladness',
  'Happiness',
  'Jubilation',
  'Elation',
  'Satisfaction',
  'Ecstasy',
  'Euphoria',
  'Zest',
  'Enthusiasm',
  'Zeal',
  'Excitement',
  'Thrill',
  'Exhilaration',
  'Contentment',
  'Pleasure',
  'Pride',
  'Triumph',
  'Optimism',
  'Eagerness',
  'Hope',
  'Enthrallment',
  'Rapture',
  'Relief',

  'Surprise',
  'Amazement',
  'Astonishment',

  'Anger',
  'Irritability',
  'Aggravation',
  'Agitation',
  'Annoyance',
  'Grouchy',
  'Grumpy',
  'Crosspatch',
  'Exasperation',
  'Frustration',
  'Rage',
  'Anger',
  'Outrage',
  'Fury',
  'Wrath',
  'Hostility',
  'Ferocity',
  'Bitterness',
  'Hatred',
  'Scorn',
  'Spite',
  'Vengefulness',
  'Dislike',
  'Resentment',
  'Disgust',
  'Revulsion',
  'Contempt',
  'Loathing',
  'Envy',
  'Jealousy',
  'Torment',
  "Schadenfreude (joy in others' harm)",

  'Sadness',
  'Suffering',
  'Agony',
  'Anguish',
  'Hurt',
  'Sadness',
  'Depression',
  'Despair',
  'Gloom',
  'Glumness',
  'Unhappiness',
  'Grief',
  'Sorrow',
  'Woe',
  'Misery',
  'Melancholy',
  'Disappointment',
  'Dismay',
  'Displeasure',
  'Shame',
  'Guilt',
  'Regret',
  'Remorse',
  'Neglect',
  'Alienation',
  'Defeatism',
  'Dejection',
  'Embarrassment',
  'Homesickness',
  'Humiliation',
  'Insecurity',
  'Insult',
  'Isolation',
  'Loneliness',
  'Rejection',
  'Sympathy',
  'Pity',
  'Mono no aware (awareness of the transience of all things)',
  'Sympathy',
  'Saudade (melancholic longing)',

  'Fear',
  'Horror',
  'Alarm',
  'Shock',
  'Fear',
  'Fright',
  'Horror',
  'Terror',
  'Panic',
  'Hysteria',
  'Mortification',
  'Nervousness',
  'Anxiety',
  'Suspense',
  'Uneasiness',
  'Apprehension',
  'Worry',
  'Distress',
  'Dread',
];
