/**
 * these items may individually be subject to a different license than
 * the main project. See the LICENSE file in this directory for more details.
 *
 * To the best of my ability, I've included comments describing the source of
 * each group of items.
 */
export const locations = [
  // Cleaned up from https://improwiki.com/en/wiki/improv/list_of_places.
  // License: https://improwiki.com/en/lizenz
  'Observation tower',
  'Farmhouse',
  'Shop',
  'High-rise building',
  'Chicken coop',
  'Barracks',
  'Chapel/cathedral',
  'Monastery',
  'Town hall',
  'Skyscraper',
  'Stadium',
  'Pyramid',
  'Prison',
  'Ice station',
  'Eiffel tower',
  "Forester's house",
  'Law firm',
  'Hardware store',
  'Office',
  'Factory',
  'Assembly line',
  'Hairdresser',
  'Open-plan office',
  'Harbor',
  'Internet cafe',
  'Orthodontist',
  'Kindergarten classroom',
  'High school classroom',
  'Indoor market',
  'Open-air market',
  'Trade-fair stand',
  'Gym',
  'Nail salon',
  "Butcher's shop",
  'Tanning salon',
  "Tax adviser's office",
  'Supermarket',
  'Laundromat',
  'Ad agency',
  'Sausage stand',
  'Dentist',
  'Glacier',
  'Forest',
  'Beach',
  'Meadow',
  'Desert',
  'Park',
  'Rainforest',
  'Desert oasis',
  'Savannah',
  'Waterfall',
  'Library',
  'School',
  'Cinema/theater',
  'Museum',
  'Bedroom',
  'Living room',
  'Kitchen',
  'Garage',
  'Music room',
  'Library',
  'Guest room',
  'Basement/cellar',
  'Balcony',
  'Greenhouse',
  'The Moon',
  'Heaven',
  'Hell',
  'Spaceship',
  'Space station',
  'Time machine',
  'Aircraft',
  'Camper/RV',
  'Motorcycle',
  'Train',
  'Zeppelin',
  'Bus',
  'Under a bridge',
  'Crematorium',
  'Cemetery',
  'Zoo',
  'Circus',

  // From my own head and things I've heard:
  'Vineyard/winery',
  'Bar/pub',
  'The Rainforest Cafe',
  'Starbucks',
  "McDonald's",
  'Backyard bonfire',
  'Submarine',
];
