/**
 * these items may individually be subject to a different license than
 * the main project. See the LICENSE file in this directory for more details.
 *
 * To the best of my ability, I've included comments describing the source of
 * each group of items.
 */
export const occupations = [
  // Cleaned up from https://improwiki.com/en/wiki/improv/occupations_list.
  // License: https://improwiki.com/en/lizenz
  'Animal keeper',
  'Architect',
  'Asparagus harvester',
  'Astronaut',
  'Auctioneer',
  'Baker',
  'Bar keeper',
  'Beautician',
  'Bee keeper',
  'Bicycle messenger',
  'Biologist',
  'Book seller',
  'Bouncer',
  'Boxer',
  'Brick layer',
  'Butcher',
  'Call-center agent',
  'Camera crew',
  'Captain',
  'Carpenter',
  'Cemetery keeper',
  'Chancellor',
  'Chef',
  'Chemist',
  'Chimney sweeper',
  'Singer',
  'Circus artist',
  'Comedy author',
  'Composer',
  'Computer scientist',
  'Concrete worker',
  'Conductor',
  'Dentist',
  'Diet counselor',
  'Director',
  'Disc jockey',
  'Door keeper',
  'Dress maker',
  'Driving instructor',
  'Educator',
  'Electrician',
  'Energy consultant',
  'Estate agent',
  'Event manager',
  'Fire fighter',
  'Florist',
  'Gardener',
  'Geriatric nurse',
  'Goldsmith',
  'Head hunter',
  'High school teacher',
  'Stay-at-home parent',
  'Human resources manager',
  'Hunter',
  'Ice cream vendor',
  'Interior designer',
  'Interpreter',
  'Jazz musician',
  'Journalist',
  'Judge',
  'Lawyer',
  'Legal expert',
  'Librarian',
  'Lifeguard',
  'Mail carrier',
  'Market researcher',
  'Relationship counselor',
  'Massage therapist',
  'Meteorologist',
  'Minister of defense',
  'Model',
  'Mountaineer',
  'Music teacher',
  'Nurse',
  'Obstetrician',
  'Optician/Optometrist',
  'Painter',
  'Pathologist',
  'Pharmacist',
  'Photographer',
  'Physician',
  'Physicist',
  'Piano maker',
  'Pilot',
  'Plumber',
  'Priest',
  'Speech prompter',
  'Election analyst',
  'Puppeteer',
  'Roofer',
  'Salesperson',
  'Santa',
  'Shepherd',
  'Ship builder',
  'Soccer referee',
  'Speech writer',
  'Sports instructor',
  'Stone mason',
  'Stunt double',
  'Swimming pool attendant',
  'Taxi driver',
  'Tour guide',
  'Track welder',
  'Train driver',
  'Veterinarian',
  'Violin maker',
  'Watch maker',

  // From my own head and things I've heard:
  'Bigfoot',
  'The Loch Ness Monster',
  'Jester',
  'King',
  'Queen',
];
